voxelized_pointcloud:
  voxel_size: 0.05
  dim_mins: null
  dim_maxs: null
  feature_pool_method: "mean"
  limit_voxels: null

feature_slam:
  _target_: preprocessing.unproject_rgbd_feature_slam.UnprojectRGBDFeatureSLAM
  image_feature_generator:
    _target_: preprocessing.image_features.image_embedding.EmbeddingFeatureImageGenerator
    image_feature_encoder:
      _target_: preprocessing.image_features.dino_encoder.DINOV2Encoder
      version: "base"
      device: cuda
    device: cuda
  device: cuda


# This determines where the pointclouds go
cache_path: "/fsx-cortex/kmj/debug/locate3d/preprocessing-release"
store_data_for_process_action: True
keep_frame_history: False
batch_size: 1

learned_location_predictor: False

skip_process_action: False
classpath: pretrain.pointcloud_featurizer.FeatureLifter3DTransform
